### ISSUE TITLE
Docs-Website can not be viewed

### ISSUE THREAD

**Issue by gitcode6** [cdmdotnet/Manatee.Trello#358]
The docs-Website (https://gregsdennis.github.io/Manatee.Trello) can not be viewed!

**Comment by gregsdennis** [comment]
That's probably because I don't own this project anymore.  The source for the docs are in [this folder](https://github.com/cdmdotnet/Manatee.Trello/tree/master/docs_source).

**Comment by gitcode6** [comment]
Oh, ok thanks for letting me know.
